### ISSUE TITLE
Is this project currently limited to 32bit platforms?

### ISSUE THREAD

**Issue by Ninlives** [fosslinux/live-bootstrap#141]
First of all, thanks for this amazing project!
I found that the instructions in README and the parts.rst are specific to x86 platform, are there any plan to expand this project to x86_64 platforms? Is the mes-m2 a main blocker to port this project to 64bit platforms?

**Comment by oriansj** [comment]
Yes however some tools may require modification to enable such ports.

**Comment by fosslinux** [comment]
The story here is complex. TLDR is yes, limited to 32-bit.

I do not plan to expand this to 64-bit until 32-bit is completed, just as a starter.

The primary blockers are that;

- tinycc mes version does not work on x86_64
- some older packages we have don't work with x86_64

there are probably other smaller issues we just haven't found yet.

I have a strong feeling, getting x86_64 working is going to be very difficult, and it will be better to just cross-compile to x86_64 at some appropriate point in the bootstrap chain.

**Comment by stikonas** [comment]
> The story here is complex. TLDR is yes, limited to 32-bit.
> 
> I do not plan to expand this to 64-bit until 32-bit is completed, just as a starter.
> 
> The primary blockers are that;
> 
>     * tinycc mes version does not work on x86_64
> 
>     * some older packages we have don't work with x86_64
> 
> 
> there are probably other smaller issues we just haven't found yet.
> 
> I have a strong feeling, getting x86_64 working is going to be very difficult, and it will be better to just cross-compile to x86_64 at some appropriate point in the bootstrap chain.

I'm not so pessimistic but yes, it will take quite a bit of work.
And other arches even harder (e.g. getting it to work with risc-v).

Still, writing a non-optimizing compiler is easier than one might initially expect.

**Comment by nanonyme** [comment]
I'm not sure how relevant direct x86_64 is anyway since you most likely end up building your own toolchain on top of this project's deliverables anyway (given the old GCC version) and at that point it's quite easy to cross-compile. non-x86 would be more exciting prospect since x86_64 is not a free platform.

**Comment by stikonas** [comment]
We'll probably get to newer GCC version here, since it's quite easy here.

As for other platforms, they need quite a bit of work, especially RISC-V. stage0-posix now has fairly good arch support (x86, x86_64, aarch64, riscv32/riscv64) but mescc needs to be ported to RISC-V, and then we need to sort out TCC. That's quite a bit of work that will take a long time unless more people join in.

**Comment by nanonyme** [comment]
Well, there are other reasons for using this project as binary seed for actual toolchain instead of using output as toolchain well than just GCC version. Switching libc also involves quite some steps on top. Of course it depends a lot on who the consumer is. For someone like distro the problem to solve may be how to get existing toolchain bootstrapped while for another project adopting live-bootstrap output directly may be a good call. In distro use case there probably is already working cross-compilation externally but I suppose not everyone has that.

**Comment by stikonas** [comment]
> Well, there are other reasons for using this project as binary seed for actual toolchain instead of using output as toolchain well than just GCC version. Switching libc also involves quite some steps on top. Of course it depends a lot on who the consumer is. For someone like distro the problem to solve may be how to get existing toolchain bootstrapped while for another project adopting live-bootstrap output directly may be a good call. In distro use case there probably is already working cross-compilation externally but I suppose not everyone has that.

I agree that there are other reasons, I'm not saying consumers should not rebuild everything. I was just pointing out that we should get newer GCC here too. In any case, a lot of stuff in the output of live-bootstrap is built with older intermediate toolchains of live-bootstrap, e.g. tcc or older GCC 4.0.4. So rebuild is good to do.

**Comment by fosslinux** [comment]
I am going to close this issue now, as for now, we aren't going to be seeing x86 (even though it would be nice to have in the future). Different issues can be opened for those at later dates.
