### ISSUE TITLE
Clarification on 32-bit kernel requirement

### ISSUE THREAD

**Issue by USA-RedDragon** [fosslinux/live-bootstrap#212]
Hello,

I am attempting to extend this project to AArch64, and just had a question. Could someone clarify technically why the README states

> Provide a kernel (vmlinuz file) as the name kernel in the root of the repository. **This must be a 32-bit kernel.**

Is it just because the only support architecture at this point is x86?

Thanks!

**Comment by fosslinux** [comment]
Yes. The only currently supported architecture is x86. The AMD64 architecture is also supported (using 32-bit binaries). But, if a kernel is used, the 32-bit kernel requirement is because of the use of `kexec-tools`, which does not support multiarch kernels (at least for the version we use).

Regarding extending this project to AArch64, I would strongly recommend coming and chatting about it on IRC (libera server, #bootstrappable).

There are a significant number of missing components that would be needed before live-bootstrap could run on AArch64. Primarily;

- mes needs to be able to build tcc (unsure re: status of this)
- tcc 0.9.26 needs to work successfully on AArch64
- i assume that some work would be needed on older kernels.
