### ISSUE TITLE
Question about x86_defs.M1

### ISSUE THREAD

**Issue by FransFaase** [fosslinux/live-bootstrap#280]
I have been working on a program to parse the kaem files in order to construct a list of all the input source and binary files that are used.

I have a question about the following lines taken from lines 48 to 51 in the file [`sysa/mes-0.24.2/mes-0.24.2.kaem`](https://github.com/fosslinux/live-bootstrap/blob/master/sysa/mes-0.24.2/mes-0.24.2.kaem):
```
# Fixes to support newer M2-Planet
catm x86_defs.M1 /M2libc/x86/x86_defs.M1 lib/m2/x86/x86_defs.M1
cp x86_defs.M1 lib/m2/x86/x86_defs.M1
rm x86_defs.M1
```
This seems to create the file `x86_defs.M1` from the concatination of this file from two different locations and then copy it to one of these locations. However the file `lib/m2/x86/x86_defs.M1` seems to be an input file, already present, when I look at [`oriansj/mes-m2/lib/m2/x86/x86_defs.M1`](https://github.com/oriansj/mes-m2/blob/master/lib/m2/x86/x86_defs.M1).

Furthermore the `/M2libc/x86/x86_defs.M1` presumes there is a directory `M2libc` in the root. I fail to see how this directory is created and filled.

**Comment by fosslinux** [comment]
`lib/m2/x86/x86_defs.M1` is the file used by `mescc`'s invocation of `M1` (which is what it compiles to) that holds a variety of defines for the X86 architecture. This is upstream's tree because there is no guarantee a system that has `M1` has `x86_defs.M1` anywhere.

The recent project `M2libc` has now made a location for this, other common files, libc functions, etc for M2-Planet and associated ecosystem. However `mescc` does not utilise this. Newer versions of M2-Planet utilise M1 definitions that are not in mes's in-tree version of `x86_defs.M1`. We need M2-Planet to work because mes is built with M2-Planet (and `kaem.run` https://github.com/fosslinux/live-bootstrap/blob/master/sysa/mes-0.24.2/mes-0.24.2.kaem#L56 from mes uses in-tree `x86_defs.M1`). By concating the two we ensure that everything `M2-Planet` *and* `mescc` expect to be in that file is there.

This concated file replaces the original.

`/M2libc` is expected to be at the root. The root contains the contents of `stage0-posix-x86`. https://github.com/fosslinux/live-bootstrap/tree/master/sysa/stage0-posix. See https://github.com/fosslinux/live-bootstrap/blob/master/sysa.py#L97 for how `rootfs.py` does this.

**Comment by FransFaase** [comment]
Thanks for the clear and detailed answer!
