### ISSUE TITLE
Add Rust bootstrap from source 

### ISSUE THREAD

**Issue by ajherchenroder** [fosslinux/live-bootstrap#300]
With more and more projects using rust in parts of their code base does it make sense to bootstrap rust from C as part of this process ?

I realize that it’s out of scope for V 1.0 but it may be worth thinking about.

**Comment by stikonas** [comment]
This is somewhat tricky question. It would be nice BUT:
* At the moment live-bootstrap is x86 only (though with some patches I do have early steps up to GNU mes working on some other arches). But rust bootstrap is very problematic on x86 (or any other 32-bit arch in general) due to very heavy memory use and does not fit into 3 GiB of RAM that we have access on 32-bit arches.
* I takes a really long time to do it with mrustc/rustc chain.

That said I do maintain rust bootstrap chain in my gentoo-bootstrap overlay (https://gitlab.com/stikonas/gentoo-bootstrap/-/tree/master/dev-lang/rust).

**Comment by fosslinux** [comment]
I think that this is out of scope for live-bootstrap core entirely.

Pros for including rust:
- It's being used more widely.
- It might be useful for projects that build ontop of live-bootstrap.

Cons for including rust:
- It would exist without any clearly defined usecase. Every other piece of software in live-bootstrap exists with a clear reason, rust is not required for a basic Linux system. (Note that Python is in the core, largely because recent glibc requires Python. Even though we don't use glibc,)
- It takes a **insanely long** time to bootstrap rustc. This would at least 3x the time it takes to run live-bootstrap.
- No x86 path for rust at this time.

---

My preferred solution.

After 1.0, I'm looking to design a bit of a more robust plugin system that makes it easier to integrate with live-bootstrap. The goal of this will essentially be to reduce duplication between consumers of live-bootstrap

Rust is pretty much the exact kind of thing I envisage people using the plugin system for.

(The plugin system will also reduce feature creep in live-bootstrap core, because we could add many many things that are not required for the basic toolchain but will add a lot of maintenance complexity.)

**Comment by ajherchenroder** [comment]
I like your plugin concept. On reflection I think that’s the right way to go. I’ve been watching this project for a while and it’s mature enough that I started planning out a full  Gentoo desktop bootstrap with live-bootstrap as the initial stage. The one issue that I couldn’t get a handle on was bootstrapping rust. I now have an outline of a plan. Thanks for the good responses. As far as I’m concerned you can close this out if you want.

**Comment by stikonas** [comment]
I suggest starting Gentoo bootstrap with just something that gets us to something like stage3 (in a scripted way). Rest can be easily done with portage overlays.

**Comment by fosslinux** [comment]
I'd love to hear updates on bootstrapping Gentoo! #bootstrappable on libera.chat is where most of the informal chatter goes on. For now, I'll close this issue.
