### ISSUE TITLE
Util-Linux-2.19.1 Gives A GPF During bootstrap

### ISSUE THREAD

**Issue by ajherchenroder** [fosslinux/live-bootstrap#307]
Util-Linux-2.19.1 Gives A GPF during bootstrap. 

Command run:
./rootfs.py -q  -p --build-kernels --update-checksums

Fault Data:

EXCEPTION: General Protection: error code 0x00000000 (0b0)
Process '/usr/libexec/gcc/i386-unknown-linux-musl/4.0.4/collect2' with pid 16296
 cs: 0x0000001b	eip: 0x080587df	efl: 0x00010246	 ss: 0x00000023	esp: 0xbffff418
eax: 0xffffffda	ebx: 0x00000001	ecx: 0xbffff444	edx: 0x00000000
esi: 0x00000008	edi: 0xbffff430	esp: 0xca28bfe4	ebp: 0x00000000
 ds: 0xc9220023	 es: 0xbfff0023	 fs: 0x00000023	 gs: 0x00000023
configure: error: in `/sysa/util-linux-2.19.1/build/util-linux-2.19.1':
configure: error: cannot compute suffix of executables: cannot compile and link
See `config.log' for more details.
Subprocess error 1
ABORTING HARD

WARNING: the last user process has exited. The kernel will stop itself.
kexec_linux: kernel file size: 2360004191
kexec_linux: Invalid kernel signature

**    Safe to Power Off    **
            -or-
** Press Any Key to Reboot **

Fault is reproducible with the given command line. Fault does not occur with a chroot build. I am holding onto the /tmp directory from the last build. if you need anything out of there please let me know.

**Comment by rick-masters** [comment]
This started with the upgrade to musl-1.2.4. For me most qemu (w/kernel-bootstrap) builds fail now but not all of them.

**Comment by ajherchenroder** [comment]
I's this possibly a qemuism? It's interesting to me that both a chroot and bwrap build work and a qemu build doesn't. As far as I can tell all three approaches build musl-1.2.4. Have you tried it on bare metal? I was going to but I just found out that all of my operational machines are EUFI class 3 and can't do a BIOS boot.

**Comment by rick-masters** [comment]
I think it is very unlikely to be a qemu issue. This problem didn't happen before the musl-1.2.3 -> musl-1.2.4 upgrade.

The qemu builds now bootstrap through primitive kernels which are built and run until there are enough tools to build and launch Linux. The GPF faults occur when the Fiwix kernel is running and that kernel only implements a limited set of system calls. The introduction of musl-1.2.4 has likely triggered a new problem related to the unimplemented syscalls. For example, Fiwix doesn't support threading-related system calls so threads and thread local storage won't work reliably.

chroot and bstrap use the host Linux kernel so they don't have the same problems.

**Comment by ajherchenroder** [comment]
well, we'll find out. I had already queued up a couple of runs with various memory and emulation settings to go over night. If they all fail then we can pretty much rule out qemu configuration as the issue. It will be a data point one way or another.

**Comment by ajherchenroder** [comment]
You were correct. None of my qemu builds from last night succeeded. This morning I ran a git revert to pull out the musl- 1.2.4 commit and it and the bootstrap completed successfully. It appears that we need musl-1.2.3 for the kernel bootstrap to succeed. I would think that the next thing to test is when we can successfully cut over to 1.2.4. My guess is that it should be right before the sysb transition. I'm not quite sure just how to do that right now but I'll figure it out.

**Comment by rick-masters** [comment]
@ajherchenroder 
I am pursuing another way to resolve this. I have preliminary indications that the problem does not occur when I use a more recent version of Fiwix (with live-bootstrap related patches applied). It will take quite a bit of testing to confirm and identify which changes to Fiwix made the difference and understand why. If this pans out we may be able to keep musl-1.2.4.

Note that we already rebuild musl-1.2.4 right before sysb to re-enable the threading and clone functionality for use with Linux. So, if we need to use musl-1.2.3 early for Fiwix then we already have a transition to 1.2.4 ready.

**Comment by rick-masters** [comment]
I think I have this figured out. The faults are occurring in gcc's collect2 program around creating temporary files. If a unique filename cannot be created (because one already exists with the same name) the program aborts. I suspect that gcc is creating a temporary file with the .c suffix and then launches collect2 which tries to create one with the same name.

The musl-1.2.4 implementation of __randname which is used indirectly by mkstemps is different from the musl-1.2.3 implementation. The 1.2.3 included different sources of randomness such as the address from the pointer to the file template. The 1.2.4 implementation doesn't use that and relies more on the time of day.

The version of Fiwix currently in live-bootstrap uses has a coarse timer that feeds the gettimeofday system call. So it is possible to get the same time across multiple calls until mkstemps fails. 

A couple of weeks ago @mikaku added more granularity to the timer in this commit: https://github.com/mikaku/Fiwix/commit/d588c34a2f39d67f7f194331ec9b3ee40007f69a
Including that improvement to Fiwix appears to resolve this problem. I'll produce an updated Fiwix package and submit a PR soon.
