### ISSUE TITLE
Question about gcc 4.7.4 step

### ISSUE THREAD

**Issue by zombiezen** [fosslinux/live-bootstrap#483]
Hey there, this isn't an issue with the repository, but a question on how it operates. As context, I'm trying to use live-bootstrap as the basis for a source bootstrap for my [zb build tool](https://github.com/256lights/zb). It operates similarly to Nix, in that each step is run in an isolated chroot that only includes inputs from previous steps that are explicitly included. I have made slight modifications to live-bootstrap to operate under these conditions, but kudos to y'all, it mostly just works out of the box. 😁

However, I've been stuck for the better part of a month on trying to get the gcc 4.7.4 to build. I've posted the error log in [this issue comment](https://github.com/256lights/zb/issues/69#issuecomment-2471121021). In short, the configure phase for libcpp, it tries and fails to use a C++ preprocessor instead of the already built `cpp` in the `$PATH`. (The `$PATH` includes gcc 4.0.4, automake 1.11.2, and autoconf 2.64 as built from previous stages of live-bootstrap.)

Any ideas what might be going on? I'm not especially skilled in autoconf/automake arcana, so insights are eluding me. I'm not expecting anyone to fully debug this for me, but I would appreciate any assistance that folks could provide. Even if someone can show me the log output of this step on a working version of live-bootstrap would be tremendously helpful. Thank you!

**Comment by stikonas** [comment]
The log of the CI run can be found at https://productionresultssa7.blob.core.windows.net/actions-results/7af40ce1-fff5-402f-825c-1872ad3dd428/workflow-job-run-e3e09517-e2d0-526c-ac85-c643ee3a708e/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-17T17%3A48%3A14Z&sig=SFXGBEstTaHqJjdRluQLnNPMePPYBxTtiRNLVq3z%2FvM%3D&ske=2024-11-18T03%3A42%3A49Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-17T15%3A42%3A49Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-08-04&sp=r&spr=https&sr=b&st=2024-11-17T17%3A38%3A09Z&sv=2024-08-04

(it will probably be garbage collected later but for now link works).

I can see
```
2024-10-26T12:54:50.3463245Z checking whether byte ordering is bigendian... no
2024-10-26T12:54:50.3606289Z checking how to run the C++ preprocessor... /lib/cpp
2024-10-26T12:54:50.3677561Z configure: error: in `/steps/gcc-4.7.4/build/gcc-4.7.4/build/gcc':
2024-10-26T12:54:50.3678725Z configure: WARNING: C++ preprocessor "/lib/cpp" fails sanity check
2024-10-26T12:54:50.3679757Z See `config.log' for more details.
2024-10-26T12:54:50.3717506Z checking for unordered_map... no
```
Hard to tell why it is different. I could even be because of different prefix (i.e. not /usr)
